CONTAINER Otest
{
	NAME Otest;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLUMNS 3;

		REAL TEST_PARAM_1    { UNIT REAL; MIN 0.0; MAX 1.0; STEP 0.1; CUSTOMGUI ROTARYKNOB; }
		REAL TEST_PARAM_2    { UNIT REAL; MIN 0.0; MAX 5.0; STEP 0.1; CUSTOMGUI ROTARYKNOB; VALUE_IN_KNOB; }
		REAL TEST_PARAM_3    { UNIT REAL; MIN 0.0; MAX 10.0; STEP 0.1; CUSTOMGUI ROTARYKNOB; HIDE_VALUE; }
	}
}
